### ISSUE TITLE
함수의 위치

### ISSUE THREAD

**Issue by hello-im-yj** [Boostcamp-Recsys9/codingtest-practice#1]
https://github.com/boostcamp-recsys09/codingtest-practice/blob/2cbd42532ad608cae1c08d2d78f742269d3f1949/week2/%EC%9C%A4%EC%84%B1/5(%EC%8B%9C%EA%B0%84%EC%B4%88%EA%B3%BC).py#L6

solution 함수 안에서 사용된 함수가 
solution 함수 뒤에 정의되어 있는데, 
이렇게 해도 오류 없이 실행이 되나요?

**Comment by JangYunSeong** [comment]
vscode상에서는 안되는데 프로그래머스 에서는 solution함수를 제일 늦게 선언하는거 같아서 상관없을거 같습니다!

**Comment by hello-im-yj** [comment]
아 main이 따로 있는 구조이군요! 감사합니다~
